[workspace]
members = [
    "game",
    "map",
    "map/chunk_manager",
    "biomes",
    "chunk",
    "tile",

    "unit",

    "menu",

    "coords",
]

[workspace.dependencies]
sdl2_ttf = "0.25"
sdl2 = "0.37"
sdl2-sys = "0.37"
