[package]
name = "chunk_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
sdl2 = "0.37"
biomes = { path="../../biomes"}
chunk = { path="../../chunk"}
tile = { path="../../tile"}
rand = "0.8.5"
