[package]
name = "chunk"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3" # pour la sérialisation binaire
tile = { path="../tile"}
biomes = { path="../biomes"}
toml = "0.8.18"
rand = "0.8.5"