[package]
name = "tile"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bitflags = { version = "2.4", features = ["serde"] }
coords = {path="../coords"}
