[[biomes]]
name = "Plain"
seed = 0
scale = 0.3
rock_threshold = 0.7
grass_threshold = 0.2
dirt_threshold = 0.0
water_threshold = -0.5
magma_threshold = -1.1

[[biomes]]
name = "Mountain"
seed = 0
scale = 0.6
rock_threshold = 0.6
grass_threshold = 0.3
dirt_threshold = 0.0
water_threshold = -0.2
magma_threshold = -0.8

[[biomes]]
name = "Forest"
seed = 0
scale = 0.4
rock_threshold = 0.5
grass_threshold = 0.1
dirt_threshold = -0.1
water_threshold = -0.4
magma_threshold = -0.9
