
[[biomes]]
name = "Default"

[[biomes.noise_layers]]
scale = 10.0
weight = 1.0



[[biomes.thresholds]]
min = -1.0
max = -0.9
tile_type = "Dirt"
[[biomes.thresholds]]
min = -0.9
max = 0.0
tile_type = "Dirt"

[[biomes.thresholds]]
min = 0.0
max = 1.0
tile_type = "Grass"




























[[biomes]]
name= "Ocean"

[[biomes.noise_layers]]
scale = 0.1
weight = 1.0
[[biomes.noise_layers]]
scale = 2.0
weight = 0.3
[[biomes.noise_layers]]
scale = 1.0
weight = 0.1


[[biomes.thresholds]]
min = -64.0
max = 0.0
tile_type = "Deep_water"
[[biomes.thresholds]]
min = 0.0
max = 64.0
tile_type = "Water"














[[biomes]]
name= "Coast"

[[biomes.noise_layers]]
scale = 1.0
weight = 1.0
[[biomes.noise_layers]]
scale = 0.1
weight = 0.1


[[biomes.thresholds]]
min = -1.0
max = -0.7
tile_type = "Water"

[[biomes.thresholds]]
min = -0.7
max = 0.0
tile_type = "Sand"

[[biomes.thresholds]]
min = 0.0
max = 0.5
tile_type = "Dirt"

[[biomes.thresholds]]
min = 0.5
max = 1.0
tile_type = "Grass"




















[[biomes]]
name = "Plain"

[[biomes.noise_layers]]
scale = 1.0
weight = 1.0



[[biomes.thresholds]]
min = -1.0
max = 1.0
tile_type = "Dirt"



















[[biomes]]
name = "Hill"

[[biomes.noise_layers]]
scale = 1.0
weight = 1.0

[[biomes.thresholds]]
min = -1.0
max = 1.0
tile_type = "Grass"

























[[biomes]]
name= "Mountain"

[[biomes.noise_layers]]
scale = 1.0
weight = 1.0

[[biomes.thresholds]]
min = -1.0
max = 1.0
tile_type = "Rock"




















