
[[biomes]]
name = "Default"
base_height = 0.0
height_variation = 0.0

[[biomes.noise_layers]]
scale = 5.0
weight = 1.0
[[biomes.noise_layers]]
scale = 1.0
weight = 0.5
[[biomes.noise_layers]]
scale = 0.5
weight = 0.2
[[biomes.noise_layers]]
scale = 0.1
weight = 0.01



[[biomes.thresholds]]
min = -1.0
max = -0.9
tile_type = "Dirt"
[[biomes.thresholds]]
min = -0.9
max = 0.0
tile_type = "Dirt"

[[biomes.thresholds]]
min = 0.0
max = 1.0
tile_type = "Grass"


[[biomes]]
name= "Ocean"
base_height = 0.0
height_variation = 0.0

[[biomes.noise_layers]]
scale = 0.05
weight = 0.7
[[biomes.noise_layers]]
scale = 2.0
weight = 0.5
[[biomes.noise_layers]]
scale = 1.0
weight = 0.1

[[biomes.thresholds]]
min = -1.0
max = 0.5
tile_type = "Water"

[[biomes.thresholds]]
min = 0.5
max = 0.6
tile_type = "Sand"

[[biomes.thresholds]]
min = 0.6
max = 0.7
tile_type = "Dirt"

[[biomes.thresholds]]
min = 0.7
max = 0.8
tile_type = "Grass"

[[biomes.thresholds]]
min = 0.8
max = 1.0
tile_type = "Rock"







[[biomes]]
name = "Plain"
base_height = 0.4
height_variation = 0.8

[[biomes.noise_layers]]
scale = 16.0
weight = 1.0

[[biomes.noise_layers]]
scale = 8.0   # Plus détaillé
weight = 0.7

[[biomes.noise_layers]]
scale = 4.0   # Couches fines
weight = 0.4

[[biomes.thresholds]]
min = -1.0
max = -0.2
tile_type = "Water"

[[biomes.thresholds]]
min = -0.2
max = 0.0
tile_type = "Sand"

[[biomes.thresholds]]
min = 0.0
max = 0.1
tile_type = "Dirt"

[[biomes.thresholds]]
min = 0.1
max = 0.3
tile_type = "Grass"

[[biomes.thresholds]]
min = 0.3
max = 0.6
tile_type = "Rock"

[[biomes.thresholds]]
min = 0.6
max = 1.0
tile_type = "Rock"







[[biomes]]
name = "Hill"
base_height = 0.7
height_variation = 0.3

[[biomes.noise_layers]]
scale = 8.0
weight = 1.0

[[biomes.noise_layers]]
scale = 8.0   # Plus détaillé
weight = 0.7

[[biomes.noise_layers]]
scale = 4.0   # Couches fines
weight = 0.4

[[biomes.thresholds]]
min = -1.0
max = 0.1
tile_type = "Dirt"

[[biomes.thresholds]]
min = 0.1
max = 0.5
tile_type = "Grass"

[[biomes.thresholds]]
min = 0.5
max = 1.0
tile_type = "Rock"












[[biomes]]
name= "Mountain"
base_height = 0.0
height_variation = 0.0

[[biomes.noise_layers]]
scale = 0.2
weight = 0.7
[[biomes.noise_layers]]
scale = 0.1
weight = 0.5
[[biomes.noise_layers]]
scale = 1.5
weight = 0.2

[[biomes.thresholds]]
min = -1.0
max = -0.9
tile_type = "Water"

[[biomes.thresholds]]
min = -0.9
max = -0.2
tile_type = "Dirt"

[[biomes.thresholds]]
min = -0.2
max = 0.2
tile_type = "Grass"

[[biomes.thresholds]]
min = 0.2
max = 1.0
tile_type = "Rock"



















[[biomes]]
name= "Coast"
base_height = 0.0
height_variation = 0.0

[[biomes.noise_layers]]
scale = 0.08
weight = 1.0
[[biomes.noise_layers]]
scale = 8.0
weight = 0.2

[[biomes.thresholds]]
min = -1.0
max = 0.5
tile_type = "Water"

[[biomes.thresholds]]
min = 0.5
max = 0.6
tile_type = "Sand"

[[biomes.thresholds]]
min = 0.6
max = 0.7
tile_type = "Dirt"

[[biomes.thresholds]]
min = 0.7
max = 0.8
tile_type = "Grass"

[[biomes.thresholds]]
min = 0.8
max = 1.0
tile_type = "Rock"







