[[biomes]]
name = "Mountain"
base_height = 0.7
height_variation = 1.2

[[biomes.noise_layers]]
scale = 32.0  # Plus large pour les montagnes
weight = 1.0

[[biomes.noise_layers]]
scale = 8.0   # Couches fines pour détails locaux
weight = 0.5

[[biomes.noise_layers]]
scale = 2.0   # Couches fines supplémentaires pour ajouter des détails
weight = 0.2

[[biomes.thresholds]]
min = -1.0
max = -0.4
tile_type = "Fluid"
fluid_type = "Water"

[[biomes.thresholds]]
min = -0.4
max = -0.1
tile_type = "Sand"

[[biomes.thresholds]]
min = -0.1
max = 0.2
tile_type = "Rock"

[[biomes.thresholds]]
min = 0.2
max = 0.5
tile_type = "Dirt"

[[biomes.thresholds]]
min = 0.5
max = 0.8
tile_type = "Grass"

[[biomes.thresholds]]
min = 0.8
max = 1.0
tile_type = "Rock"


[[biomes]]
name = "Coast"
base_height = -0.3
height_variation = 0.5

[[biomes.noise_layers]]
scale = 16.0  # Plus large pour la côte
weight = 1.0

[[biomes.noise_layers]]
scale = 4.0   # Moins de détails fins pour l'eau
weight = 0.7

[[biomes.noise_layers]]
scale = 2.0   # Détails fins pour plages et terres
weight = 0.3

[[biomes.thresholds]]
min = -1.0
max = -0.4
tile_type = "Fluid"
fluid_type = "Water"

[[biomes.thresholds]]
min = -0.4
max = -0.1
tile_type = "Sand"

[[biomes.thresholds]]
min = -0.1
max = 0.1
tile_type = "Dirt"

[[biomes.thresholds]]
min = 0.1
max = 0.3
tile_type = "Grass"

[[biomes.thresholds]]
min = 0.3
max = 0.6
tile_type = "Rock"

[[biomes.thresholds]]
min = 0.6
max = 1.0
tile_type = "Rock"


[[biomes]]
name = "Ocean"
base_height = -1.0
height_variation = 0.1

[[biomes.noise_layers]]
scale = 64.0  # Très large pour l'océan
weight = 1.0

[[biomes.noise_layers]]
scale = 8.0   # Quelques petites îles
weight = 0.4

[[biomes.noise_layers]]
scale = 2.0   # Détails fins pour îles
weight = 0.2

[[biomes.thresholds]]
min = -1.0
max = -0.3
tile_type = "Fluid"
fluid_type = "Water"

[[biomes.thresholds]]
min = -0.3
max = 0.0
tile_type = "Sand"

[[biomes.thresholds]]
min = 0.0
max = 0.1
tile_type = "Dirt"

[[biomes.thresholds]]
min = 0.1
max = 0.3
tile_type = "Grass"

[[biomes.thresholds]]
min = 0.3
max = 1.0
tile_type = "Rock"


[[biomes]]
name = "Hill"
base_height = 0.5
height_variation = 0.8

[[biomes.noise_layers]]
scale = 16.0
weight = 1.0

[[biomes.noise_layers]]
scale = 8.0   # Plus détaillé
weight = 0.7

[[biomes.noise_layers]]
scale = 4.0   # Couches fines
weight = 0.4

[[biomes.thresholds]]
min = -1.0
max = -0.2
tile_type = "Fluid"
fluid_type = "Water"

[[biomes.thresholds]]
min = -0.2
max = 0.0
tile_type = "Sand"

[[biomes.thresholds]]
min = 0.0
max = 0.1
tile_type = "Dirt"

[[biomes.thresholds]]
min = 0.1
max = 0.3
tile_type = "Grass"

[[biomes.thresholds]]
min = 0.3
max = 0.6
tile_type = "Rock"

[[biomes.thresholds]]
min = 0.6
max = 1.0
tile_type = "Rock"
