[[biomes]]
name= "Mountain"
base_height = 0.3
height_variation = 0.5

[[biomes.noise_layers]]
scale = 1.0
weight = 0.5
[[biomes.noise_layers]]
scale = 5.0
weight = 1.0


[[biomes.thresholds]]
min = -1.0
max = -0.5
tile_type = "Fluid"
fluid_type = "Magma"

[[biomes.thresholds]]
min = -0.5
max = 0.0
tile_type = "Dirt"

[[biomes.thresholds]]
min = 0.0
max = 0.2
tile_type = "Grass"

[[biomes.thresholds]]
min = 0.2
max = 1.0
tile_type = "Rock"

