[[biomes]]
name = "Plain"
base_height = 0.0
height_variation = 0.0

[[biomes.noise_layers]]
scale = 5.0
weight = 1.0
[[biomes.noise_layers]]
scale = 1.0
weight = 0.5
[[biomes.noise_layers]]
scale = 0.5
weight = 0.2
[[biomes.noise_layers]]
scale = 0.1
weight = 0.01



[[biomes.thresholds]]
min = -1.0
max = -0.9
tile_type = "Water"
[[biomes.thresholds]]
min = -0.9
max = 0.0
tile_type = "Dirt"

[[biomes.thresholds]]
min = 0.0
max = 1.0
tile_type = "Grass"
