[package]
name = "biomes"
version = "0.1.0"
edition = "2021"

[dependencies]
tile = { path="../tile"}
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3" # pour la sérialisation binaire
toml = "0.8.18"
noise = "0.9.0"
rand = "0.8.5"
